SELECT
    NivelAcao.CODCCUSTO,
    NivelUnidade.CAMPOLIVRE AS ACAO,
    NivelProjeto.CAMPOLIVRE AS PROJETO,
    NivelAcao.CAMPOLIVRE AS UNIDADE,
    NivelAcao.RECCREATEDON AS DTUNIDADE,
    NivelProjeto.RECCREATEDON AS DTPROJETO,
    NivelUnidade.RECCREATEDON AS DTACAO
FROM HUBDADOS.CorporeRM.GCCUSTO AS NivelAcao
LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelProjeto ON LEFT(NivelAcao.CODCCUSTO, 5) = NivelProjeto.CODCCUSTO
LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelUnidade ON LEFT(NivelAcao.CODCCUSTO, 12) = NivelUnidade.CODCCUSTO
WHERE
    LEN(NivelAcao.CODCCUSTO) > 15
