
SELECT    
        C.CODCCUSTO,  
        ANO = C.ANOORCAMENTO,  
        MES = I.SEQITMORCA,  
        COMPROMETIDO = I.VALOROPCIONAL1     
    FROM     
        HubDados.CORPORERM.TCONTORCAMENTARIO C  (NoLock)  
        INNER JOIN HubDados.CORPORERM.TITMCONTORCAMENTARIO I (NoLock) ON (I.CODCOLIGADA = C.CODCOLIGADA AND I.IDORCAMENTO = C.IDORCAMENTO)    
    WHERE    
		C.ANOORCAMENTO = 2025
        AND I.VALOROPCIONAL1 > 0